site_name: Guide Aion 2 Ranger
site_description: Guide PvE Aion 2 Ranger
site_url: https://stevensc92.github.io/Aion-ranger-guide/

theme:
  name: material
  language: fr

  features:
    - navigation.sections
    - navigation.top
    - toc.follow
    - content.code.copy
    - search.suggest
    - search.highlight

nav:
  - Accueil: index.md
  - Leveling:
    - Guide 1-45: leveling/index.md
    - Daevanion: leveling/daevanion.md
  - Skills:
    - Compétences & Spécialités: skills/index.md
  - Build:
    - Builds PvE: builds/index.md
  - Gameplay:
    - Macro: gameplay/macro.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - tables
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search
  - include-markdown
  - i18n:
      docs_structure: suffix
      reconfigure_material: true
      reconfigure_search: true
      fallback_to_default: true
      languages:
        - locale: fr
          name: Français
          default: true
          build: true
        - locale: en
          name: English
          build: true
          site_name: Aion 2 Ranger Guide
          site_description: Aion 2 Ranger PvE Guide
          nav_translations:
            Accueil: Home
            Leveling: Leveling
            "Guide 1-45": "Leveling Guide 1–45"
            Daevanion: Daevanion
            Skills: Skills
            "Compétences & Spécialités": "Skills & Specializations"
            Build: Builds
            "Builds PvE": "PvE Builds"
            Gameplay: Gameplay
            Macro: Macro

extra_css:
  - stylesheets/extra.css
