site_name: Guide Aion 2
site_description: Guide PvE Aion 2 Ranger
site_url: https://stevensc92.github.io/Aion-ranger-guide/

theme:
  name: material
  language: fr

  features:
    - navigation.sections
    - navigation.top
    - toc.follow
    - content.code.copy
    - search.suggest
    - search.highlight

nav:
  - Guide: index.md

markdown_extensions:
  - attr_list
  - admonition
  - tables
  - toc:
      permalink: true
      toc_depth: 3